// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD24MW2op9fycnMmiE7YgAalI0_A2VWte8',
    appId: '1:763317926836:web:f8f102da53d2ca703510e1',
    messagingSenderId: '763317926836',
    projectId: 'myshowspot-2e66e',
    authDomain: 'myshowspot-2e66e.firebaseapp.com',
    storageBucket: 'myshowspot-2e66e.firebasestorage.app',
    measurementId: 'G-SLMV87B40F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYbo7D-EOSaYW1k5PwVoQnoevD0RD9HnM',
    appId: '1:763317926836:android:c562ac38b08996b23510e1',
    messagingSenderId: '763317926836',
    projectId: 'myshowspot-2e66e',
    storageBucket: 'myshowspot-2e66e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhfhLdfBrdmNOL6u6LZwHzxW1WPhia1QQ',
    appId: '1:763317926836:ios:41c7ae71441a4ab43510e1',
    messagingSenderId: '763317926836',
    projectId: 'myshowspot-2e66e',
    storageBucket: 'myshowspot-2e66e.firebasestorage.app',
    iosBundleId: 'com.example.showspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhfhLdfBrdmNOL6u6LZwHzxW1WPhia1QQ',
    appId: '1:763317926836:ios:41c7ae71441a4ab43510e1',
    messagingSenderId: '763317926836',
    projectId: 'myshowspot-2e66e',
    storageBucket: 'myshowspot-2e66e.firebasestorage.app',
    iosBundleId: 'com.example.showspot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD24MW2op9fycnMmiE7YgAalI0_A2VWte8',
    appId: '1:763317926836:web:e65d3f73521850553510e1',
    messagingSenderId: '763317926836',
    projectId: 'myshowspot-2e66e',
    authDomain: 'myshowspot-2e66e.firebaseapp.com',
    storageBucket: 'myshowspot-2e66e.firebasestorage.app',
    measurementId: 'G-XVKVJ2D32E',
  );
}
